# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'LocationSend' do
  use_frameworks!

  # Pods for API and JSON
    pod 'Alamofire'
    pod 'SwiftyJSON'

end
